#route:
#    receiver: 'slack'

#receivers:
 #   - name: 'slack'
 #     slack_configs:
 #         - send_resolved: true
 #           text: "{{ .CommonAnnotations.description }}"
 
 #           channel: '#<channel-name>'
 #           api_url: 'https://hooks.slack.com/services/<webhook-id>
global:
  # The smarthost and SMTP sender used for mail notifications.
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'sender_mail@gmail.com'
  smtp_auth_username: 'sender_mail@gmail.com'
  smtp_auth_password: 'mail_password'
route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 10s
  receiver: 'email'
receivers:
- name: 'email'
  email_configs:
  - to: 'receiver@domain.com'
- name: 'slack'
  slack_configs:
  - send_resolved: true
    text: "{{ .CommonAnnotations.description }}"
 
    channel: '#<channel-name>'
    api_url: 'https://hooks.slack.com/services/<webhook-id>
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
